coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: true
  after_n_builds: 1
