version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/node:18.17.0-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Start server
          command: |
            npm run start &
            npx wait-on http://localhost:3000
      - run:
          name: Run Cypress tests
          command: npx cypress run
