version: 2.1

orbs:
  cypress: cypress-io/cypress@3

workflows:
  build:
    jobs:
      - cypress/run:
          node-version: 18.17.0
          start: npm run start
          wait-on: http://localhost:3000
