version: 2.1

jobs:
  cypress-test:
    docker:
      - image: cimg/node:18.17.0-browsers
    steps:
      - checkout
      - run: # Install dependencies
          command: npm ci
      - run: # Start server and wait for it to be ready
          command: |
            npm run start &
            npx wait-on http://localhost:3000
      - run: # Run Cypress tests
          command: npx cypress run

workflows:
  build_and_test:
    jobs:
      - cypress-test
