version: 2.1

orbs:
  cypress: cypress-io/cypress@3

executors:
  node-executor:
    docker:
      - image: cimg/node:18.17.0-browsers
    working_directory: ~/repo

workflows:
  build:
    jobs:
      - cypress/install
      - run-tests:
          command: run-tests
          start-command: npm run build && npm run start
          wait-on: http://localhost:3000
